from .asignacion_model import AsignacionOrden
from .insumo_model import Insumo
from .linea_orden_insumo_link import LineaOrdenInsumoLink
from .linea_orden_model import LineaOrden
from .maquina_model import Maquina
from .operario_model import Operario
from .orden_model import Orden
from .usuario_model import Usuario
from .reporte_avance_model import ReporteAvance
from .reporte_averia_model import ReporteAveria
from .prenda_model import Prenda
from .orden_venta_model import OrdenVenta
from .linea_orden_venta_model import LineaOrdenVenta
from .orden_compra_model import OrdenCompra
from .linea_orden_compra_model import LineaOrdenCompra
from .factura_model import Factura
from .movimiento_inventario_model import MovimientoInventario
